from __future__ import annotations

from django.core.management.base import BaseCommand
from django.db import connections, transaction

from apps.core.management.portal_seed import build_local_portal_seed


class Command(BaseCommand):
    help = "Bootstrap test data in the local portal database."

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Удалить тестовые записи (без drop таблиц) и пересоздать их.",
        )
        parser.add_argument(
            "--scale",
            type=int,
            default=10,
            help="Количество событий (минимум 6, базовые кейсы всегда включены).",
        )

    @transaction.atomic(using="portal")
    def handle(self, *args, **options) -> None:
        reset = options["reset"]
        scale = options["scale"]
        with connections["portal"].cursor() as cursor:
            self._ensure_schema(cursor)
            if reset:
                self._reset_test_data(cursor)
            self._seed_data(cursor, scale)
        self.stdout.write(self.style.SUCCESS("Портальная тестовая БД готова."))

    def _ensure_schema(self, cursor) -> None:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS subdivision (
                id INTEGER PRIMARY KEY,
                fullname VARCHAR(255) NOT NULL
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS events (
                id UUID PRIMARY KEY,
                date_detection TIMESTAMP NULL,
                find_subdivision_unit_id INTEGER NULL REFERENCES subdivision(id)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS offenders (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_id UUID NOT NULL REFERENCES events(id),
                first_name VARCHAR(100),
                middle_name VARCHAR(100),
                last_name VARCHAR(100),
                date_of_birth DATE
            )
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'uq_offenders_key'
                ) THEN
                    ALTER TABLE offenders
                    ADD CONSTRAINT uq_offenders_key
                    UNIQUE (event_id, first_name, middle_name, last_name, date_of_birth);
                END IF;
            END $$;
            """
        )
        cursor.execute(
            "ALTER TABLE subdivision ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT false"
        )
        cursor.execute(
            "ALTER TABLE events ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT false"
        )
        cursor.execute(
            "ALTER TABLE offenders ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT false"
        )

    def _reset_test_data(self, cursor) -> None:
        cursor.execute("DELETE FROM offenders WHERE is_test = true")
        cursor.execute("DELETE FROM events WHERE is_test = true")
        cursor.execute("DELETE FROM subdivision WHERE is_test = true")

    def _seed_data(self, cursor, scale: int) -> None:
        subdivisions, events, _docx_events = build_local_portal_seed(scale)

        for subdivision in subdivisions:
            cursor.execute(
                """
                INSERT INTO subdivision (id, fullname, is_test)
                VALUES (%s, %s, true)
                ON CONFLICT (id)
                DO UPDATE SET fullname = EXCLUDED.fullname, is_test = EXCLUDED.is_test
                """,
                [subdivision.id, subdivision.fullname],
            )

        for event in events:
            cursor.execute(
                """
                INSERT INTO events (id, date_detection, find_subdivision_unit_id, is_test)
                VALUES (%s, %s, %s, true)
                ON CONFLICT (id)
                DO UPDATE SET
                    date_detection = EXCLUDED.date_detection,
                    find_subdivision_unit_id = EXCLUDED.find_subdivision_unit_id,
                    is_test = EXCLUDED.is_test
                """,
                [event.id, event.date_detection, event.subdivision_id],
            )
            cursor.execute(
                "DELETE FROM offenders WHERE event_id = %s AND is_test = true",
                [event.id],
            )
            for offender in event.offenders:
                cursor.execute(
                    """
                    INSERT INTO offenders (
                        event_id, first_name, middle_name, last_name, date_of_birth, is_test
                    )
                    VALUES (%s, %s, %s, %s, %s, true)
                    """,
                    [
                        event.id,
                        offender.first_name,
                        offender.middle_name,
                        offender.last_name,
                        offender.date_of_birth,
                    ],
                )
