# Generated by Django 4.2 on 2025-09-17

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0002_subdivisionref_code_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тип события",
                "verbose_name_plural": "Типы событий",
            },
        ),
        migrations.CreateModel(
            name="EventTypePattern",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pattern_text", models.TextField()),
                ("koap_article", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=100)),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patterns",
                        to="reference.eventtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паттерн события",
                "verbose_name_plural": "Паттерны событий",
            },
        ),
        migrations.AddConstraint(
            model_name="eventtypepattern",
            constraint=models.UniqueConstraint(
                fields=("event_type", "pattern_text", "koap_article"),
                name="uq_event_type_pattern",
            ),
        ),
    ]
