# Generated by Django 6.0.2 on 2026-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0003_event_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="name",
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
